-- No-op migration.
-- The original generated SQL duplicated objects already created by
-- 0002_custom_request_attempts.sql and
-- 0003_order_lookup_reservations_notifications.sql, which breaks clean
-- migration runs with "already exists" errors.
